services:
  - type: web
    name: livekit-agent
    runtime: docker
    plan: standard  # Upgraded from starter for better performance
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    
    # Resource configuration
    disk:
      name: agent-disk
      mountPath: /data
      sizeGB: 10
    
    # Environment variables
    envVars:
      - key: LIVEKIT_URL
        sync: false
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CARTESIA_API_KEY
        sync: false
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    
    # Scaling configuration
    scaling:
      minInstances: 1
      maxInstances: 5
      targetCPUPercent: 70
      targetMemoryPercent: 70
    
    # Grace period for proper shutdown
    gracefulShutdownPeriodSeconds: 600 